apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test

commonLabels:
  owner: qsw

resources:
  - 00_namespace.yaml
  - 01_deployment.yaml
  - 02_service.yaml
  - 03_ingress.yaml

replicas:
  - name: deploy-simple-flask-app
    count: 3

images:
  - name: polack27/flask-app
    newTag: "0.1"

patches:
- target:
    kind: Ingress
    name: ing-flask-app
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: mydomain.org
  