name: docker_build_image
on:
  - push
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Login in Docker Hub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./flask_app.dockerfile
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:${{ github.sha }}

      - name: Scan Image
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:${{ github.sha }}
          hide-progress: false
          format: 'table'
          exit-code: 1
          severity: 'MEDIUM'
      
      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./flask_app.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:${{ github.sha }}